### ISSUE TITLE
I cannot find a way to download Borland TASM v1.01 and TLINK v2.00. Can you send it to me? Thank you.

### ISSUE THREAD

**Issue by Gogo-GITHUB** [tonypdmtr/emu6809#1]
I cannot find a way to download Borland TASM v1.01 and TLINK v2.00. Can you send it to me? Thank you.

**Comment by tonypdmtr** [comment]
Although it's very old software, I don't think it was ever free download.
Maybe you contact former Borland (now https://www.embarcadero.com) and ask them if you can get a copy from them.  They used to give older Turbo Pascal and Turbo C versions for free, so maybe they can do the same with older TASM.
